<a href="https://colab.research.google.com/github/almsalahuddin/Data-Processing-and-Visualization/blob/main/Quiz_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Quiz 12 # : CPSMA 4313 [Dr. Jacob's](https://github.com/nurfnick) Data processing visualization

## Gathering Data Conclusion

### A L M SALAHUDDIN

In [1]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

In [3]:
%%bigquery --project london-fire-service-calls
SELECT 
  COUNT(*) as total_rows
FROM `bigquery-public-data.london_fire_brigade.fire_brigade_service_calls`

   total_rows
0       32247

In [5]:
%%bigquery --project london-fire-service-calls
SELECT COUNT(*) as number_of_late_night_false_alarms
FROM `bigquery-public-data.london_fire_brigade.fire_brigade_service_calls`
WHERE incident_group = "False Alarm" AND (hour_of_call >= 22 OR hour_of_call <= 4)

   number_of_late_night_false_alarms
0                               2825

In [6]:
%%bigquery --project london-fire-service-calls
SELECT incident_group, AVG(num_pumps_attending) as avg_pumps_attending
FROM `bigquery-public-data.london_fire_brigade.fire_brigade_service_calls`
GROUP BY incident_group

    incident_group  avg_pumps_attending
0      False Alarm             1.725776
1             Fire             1.633012
2  Special Service             1.177192